# Page settings

baseurl = "https://ygurung.com/"
languageCode = "en-us"
title = "Yogendra Gurung"
copyright = "© Yogendra Gurung"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "hugo-theme-doors"

disableRSS = true
disableSitemap = true
disable404 = false

# Site information
[params]
description = "Perhaps something like I discovered that I was a visual learner while I was an IT student so I decided to choose graphics designing and my work is the demonstration of my skills at using tools such as cutvsture tool shape builder tool etc"
ogimage = "images/work1.jpg"

# Project section
[params.projects]

[[params.projects.list]]
title = "Illustrator"
description = "These are some of the images I made in Illustrator."
image = "images/work1.jpg"
w = "780"
h = "518"

# Subproject section
[params.subprojects]

[[params.subprojects.list]]
title = "Random Gloves"
description = "2023-05-28"
image = "images/gloves.svg"
w = "780"
h = "522"

[[params.subprojects.list]]
title = "Twice Logo"
description = "2023-05-29"
image = "images/twice_logo.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Random Cap"
description = "2023-05-31"
image = "images/cap.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Random T-Shirt"
description = "2023-05-30"
image = "images/t_shirt.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Teddy Bear"
description = "2023-06-01"
image = "images/teddy_bear.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Sleepy Fox"
description = "2023-06-02"
image = "images/sleepy_fox.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Awake Fox"
description = "2023-06-03"
image = "images/fox.svg"
w = "780"
h = "518"


[[params.subprojects.list]]
title = "Random Alien"
description = "2023-06-04"
image = "images/alien.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Blender Logo"
description = "2023-06-04"
image = "images/blender.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Sunset View"
description = "2023-06-05"
image = "images/evening.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "NS Logo"
description = "2023-06-05"
image = "images/blue_n.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Illustrator"
description = "2023-06-07"
image = "images/nikesh_icon.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Night View"
description = "2023-06-07"
image = "images/window_view.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Random Postcard"
description = "2023-06-09"
image = "images/Random_Postcard.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Golden Cupcake"
description = "2023-06-11"
image = "images/golden_cupcake.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Camera Icon"
description = "2023-06-11"
image = "images/camera_icon.svg"
w = "780"
h = "518"

[[params.subprojects.list]]
title = "Ice Cream"
description = "2023-06-12"
image = "images/ice_cream.svg"
w = "780"
h = "518"

# Contact section
[params.contact]
description = "I would like to hear from you. Please contact me via email or social media."
twitter = "http://twitter.com/ygurung143"
facebook = "https://facebook.com/ygurung143"
instagram = "https://instagram.com/ygurung143"
github = "https://github.com/ygurung143"
email = "yogedragurung086@gmail.com"

